In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("spotify_history.csv", sep=",", header=0)
df

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False
...,...,...,...,...,...,...,...,...,...,...,...
149855,4Fz1WWr5o0OrlIcZxcyZtK,2024-12-15 23:06:19,android,1247,On The Way Home,John Mayer,Paradise Valley,fwdbtn,fwdbtn,True,True
149856,0qHMhBZqYb99yhX9BHcIkV,2024-12-15 23:06:21,android,1515,Magical Mystery Tour - Remastered 2009,The Beatles,Magical Mystery Tour,fwdbtn,fwdbtn,True,True
149857,0HHdujGjOZChTrl8lJWEIq,2024-12-15 23:06:22,android,1283,"Stop This Train - Live at the Nokia Theatre, L...",John Mayer,Where the Light Is: John Mayer Live In Los Ang...,fwdbtn,fwdbtn,True,True
149858,7peh6LUcdNPcMdrSH4JPsM,2024-12-15 23:06:23,android,1306,I Don't Trust Myself (With Loving You),John Mayer,Continuum,fwdbtn,fwdbtn,True,True
149859,6iGU74CwXuT4XVepjc9Emf,2024-12-15 23:06:25,android,1893,God Only Knows - Mono,The Beach Boys,Pet Sounds,fwdbtn,fwdbtn,True,True

In [6]:
len(df)

149860

In [13]:
df.shape

(149860, 11)

In [7]:
df.count()

spotify_track_uri    149860
ts                   149860
platform             149860
ms_played            149860
track_name           149860
artist_name          149860
album_name           149860
reason_start         149717
reason_end           149743
shuffle              149860
skipped              149860
dtype: int64

In [14]:
df.isna().sum()

spotify_track_uri      0
ts                     0
platform               0
ms_played              0
track_name             0
artist_name            0
album_name             0
reason_start         143
reason_end           117
shuffle                0
skipped                0
dtype: int64

In [15]:
df_albums = df[["artist_name", "album_name"]].drop_duplicates()
df_albums

              artist_name                          album_name
0            The Mowgli's                Waiting For The Dawn
1           Calvin Harris                           18 Months
2            Lana Del Rey  Born To Die - The Paradise Edition
4       Empire Of The Sun                  Walking On A Dream
5            James Arthur                          Impossible
...                   ...                                 ...
149738       Jesse Welles                        Hells Welles
149739       Jesse Welles                           Patchwork
149743       Roger Miller                         Oo-De-Lally
149744       Roger Miller                    King Of The Road
149746       Roger Miller                          Super Hits

[8437 rows x 2 columns]

In [17]:
df_albums.to_csv("albums_artistas.csv", sep=",")

In [19]:
df_albums.to_excel("albums_artistas.xlsx")

In [21]:
df_albums2 = pd.read_excel("albums_artistas.xlsx")
df_albums2

      Unnamed: 0        artist_name                          album_name
0              0       The Mowgli's                Waiting For The Dawn
1              1      Calvin Harris                           18 Months
2              2       Lana Del Rey  Born To Die - The Paradise Edition
3              4  Empire Of The Sun                  Walking On A Dream
4              5       James Arthur                          Impossible
...          ...                ...                                 ...
8432      149738       Jesse Welles                        Hells Welles
8433      149739       Jesse Welles                           Patchwork
8434      149743       Roger Miller                         Oo-De-Lally
8435      149744       Roger Miller                    King Of The Road
8436      149746       Roger Miller                          Super Hits

[8437 rows x 3 columns]

In [22]:
df_albums2.drop(columns="Unnamed: 0", inplace=True)

In [23]:
df_albums2

            artist_name                          album_name
0          The Mowgli's                Waiting For The Dawn
1         Calvin Harris                           18 Months
2          Lana Del Rey  Born To Die - The Paradise Edition
3     Empire Of The Sun                  Walking On A Dream
4          James Arthur                          Impossible
...                 ...                                 ...
8432       Jesse Welles                        Hells Welles
8433       Jesse Welles                           Patchwork
8434       Roger Miller                         Oo-De-Lally
8435       Roger Miller                    King Of The Road
8436       Roger Miller                          Super Hits

[8437 rows x 2 columns]