In [1]:
import pandas as pd
import numpy as np

In [2]:
np.nan

nan

In [3]:
dados = {"A": [1, 2, np.nan], "B": [5, np.nan, np.nan], "C": [1, 2, 3]}

In [4]:
dados

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [19]:
df = pd.DataFrame(dados)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [8]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [ ]:
# Dropa apenas as linhas que possuem 2+ dados faltantes
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
# axis = 0 linha
# axis = 1 coluna
df.dropna(axis=1, thresh=2)

     A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [12]:
df.isna()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [13]:
df.isna().sum()

A    1
B    2
C    0
dtype: int64

In [14]:
df.fillna(value="Tá faltando")

             A            B  C
0          1.0          5.0  1
1          2.0  Tá faltando  2
2  Tá faltando  Tá faltando  3

In [15]:
df["A"].fillna(value="Tá faltando")

0            1.0
1            2.0
2    Tá faltando
Name: A, dtype: object

In [16]:
df["A"] = df["A"].fillna(value="Tá faltando")
df

             A    B  C
0          1.0  5.0  1
1          2.0  NaN  2
2  Tá faltando  NaN  3

In [18]:
df.fillna({"B": "Tá faltando também"})

             A                   B  C
0          1.0                 5.0  1
1          2.0  Tá faltando também  2
2  Tá faltando  Tá faltando também  3

In [22]:
df.fillna({"A": df["A"].mean(), "B": "Tá faltando"})

     A            B  C
0  1.0          5.0  1
1  2.0  Tá faltando  2
2  1.5  Tá faltando  3