In [2]:
import pandas as pd
import numpy as np

In [3]:
compras = {
    "ID_usuario": [1, 2, 1, 1, 3, 3, 2, 3],
    "Produto": ["Notebook", "Camera", "Camiseta", "Camiseta", "Caneca", "Caneca", "Calça", "Calça"],
    "Valor": [2000, 1000, 70, 60, 50, 50, 120, 100]
}

In [5]:
df = pd.DataFrame(compras)
df

   ID_usuario   Produto  Valor
0           1  Notebook   2000
1           2    Camera   1000
2           1  Camiseta     70
3           1  Camiseta     60
4           3    Caneca     50
5           3    Caneca     50
6           2     Calça    120
7           3     Calça    100

In [7]:
df.head(3)

   ID_usuario   Produto  Valor
0           1  Notebook   2000
1           2    Camera   1000
2           1  Camiseta     70

In [9]:
df.tail(3)

   ID_usuario Produto  Valor
5           3  Caneca     50
6           2   Calça    120
7           3   Calça    100

In [13]:
df["Produto"].unique()

array(['Notebook', 'Camera', 'Camiseta', 'Caneca', 'Calça'], dtype=object)

In [14]:
df["Produto"].nunique()

5

In [15]:
len(df["Produto"].unique())

5

In [17]:
df.groupby("Produto")["ID_usuario"].count()

Produto
Calça       2
Camera      1
Camiseta    2
Caneca      2
Notebook    1
Name: ID_usuario, dtype: int64

In [ ]:
# Melhor opção para contar registros
df["Produto"].value_counts()

Produto
Camiseta    2
Caneca      2
Calça       2
Notebook    1
Camera      1
Name: count, dtype: int64

In [20]:
df["Valor"] * 100

0    200000
1    100000
2      7000
3      6000
4      5000
5      5000
6     12000
7     10000
Name: Valor, dtype: int64

In [21]:
df["Valor"] / 100

0    20.0
1    10.0
2     0.7
3     0.6
4     0.5
5     0.5
6     1.2
7     1.0
Name: Valor, dtype: float64

In [22]:
def valor_agregado(valor):
    if valor >= 1000:
        return "Alto valor"
    else:
        return "Baixo valor"

In [23]:
valor_agregado(1000)

'Alto valor'

In [24]:
df["Valor"].apply(valor_agregado)

0     Alto valor
1     Alto valor
2    Baixo valor
3    Baixo valor
4    Baixo valor
5    Baixo valor
6    Baixo valor
7    Baixo valor
Name: Valor, dtype: object

In [25]:
df["Valor Agregado"] = df["Valor"].apply(valor_agregado)

In [26]:
df

   ID_usuario   Produto  Valor Valor Agregado
0           1  Notebook   2000     Alto valor
1           2    Camera   1000     Alto valor
2           1  Camiseta     70    Baixo valor
3           1  Camiseta     60    Baixo valor
4           3    Caneca     50    Baixo valor
5           3    Caneca     50    Baixo valor
6           2     Calça    120    Baixo valor
7           3     Calça    100    Baixo valor

In [27]:
def substitui(nome_produto):
    if nome_produto == "Notebook":
        return "Computador"
    else:
        return nome_produto

In [28]:
df["Produto"].apply(substitui)

0    Computador
1        Camera
2      Camiseta
3      Camiseta
4        Caneca
5        Caneca
6         Calça
7         Calça
Name: Produto, dtype: object

In [29]:
df["Produto"].apply(lambda nome_produto: "Computador" if nome_produto == "Notebook" else nome_produto)

0    Computador
1        Camera
2      Camiseta
3      Camiseta
4        Caneca
5        Caneca
6         Calça
7         Calça
Name: Produto, dtype: object

In [31]:
df["coluna_teste"] = df["Valor"].apply(lambda valor: "Mais de 500" if valor > 500 else "Menos de 500")
df

   ID_usuario   Produto  Valor Valor Agregado  coluna_teste
0           1  Notebook   2000     Alto valor   Mais de 500
1           2    Camera   1000     Alto valor   Mais de 500
2           1  Camiseta     70    Baixo valor  Menos de 500
3           1  Camiseta     60    Baixo valor  Menos de 500
4           3    Caneca     50    Baixo valor  Menos de 500
5           3    Caneca     50    Baixo valor  Menos de 500
6           2     Calça    120    Baixo valor  Menos de 500
7           3     Calça    100    Baixo valor  Menos de 500

In [34]:
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7]

In [35]:
df.columns

Index(['ID_usuario', 'Produto', 'Valor', 'Valor Agregado', 'coluna_teste'], dtype='object')

In [40]:
df.sort_values(by="Valor", ascending=False)

   ID_usuario   Produto  Valor Valor Agregado  coluna_teste
0           1  Notebook   2000     Alto valor   Mais de 500
1           2    Camera   1000     Alto valor   Mais de 500
6           2     Calça    120    Baixo valor  Menos de 500
7           3     Calça    100    Baixo valor  Menos de 500
2           1  Camiseta     70    Baixo valor  Menos de 500
3           1  Camiseta     60    Baixo valor  Menos de 500
4           3    Caneca     50    Baixo valor  Menos de 500
5           3    Caneca     50    Baixo valor  Menos de 500