In [2]:
import numpy as np
import pandas as pd

In [31]:
dados = [
    {"Nome": "Ana", "Departamento": "TI", "Salário": 6000, "Estado": "São Paulo"},
    {"Nome": "Bruno", "Departamento": "TI", "Salário": 6000, "Estado": "Rio de Janeiro"},
    {"Nome": "Carla", "Departamento": "RH", "Salário": 4000, "Estado": "São Paulo"},
    {"Nome": "Daniel", "Departamento": "RH", "Salário": 4200, "Estado": "Belo Horizonte"},
    {"Nome": "Eduardo", "Departamento": "Vendas", "Salário": 3000, "Estado": "São Paulo"},
    {"Nome": "Fernanda", "Departamento": "Vendas", "Salário": 3500, "Estado": "Rio de Janeiro"},
]

In [32]:
df = pd.DataFrame(dados)
df

       Nome Departamento  Salário          Estado
0       Ana           TI     6000       São Paulo
1     Bruno           TI     6000  Rio de Janeiro
2     Carla           RH     4000       São Paulo
3    Daniel           RH     4200  Belo Horizonte
4   Eduardo       Vendas     3000       São Paulo
5  Fernanda       Vendas     3500  Rio de Janeiro

In [19]:
df.groupby("Departamento")["Salário"].mean()

Departamento
RH        4100.0
TI        5500.0
Vendas    3250.0
Name: Salário, dtype: float64

In [20]:
df.groupby("Departamento")["Salário"].max()

Departamento
RH        4200
TI        6000
Vendas    3500
Name: Salário, dtype: int64

In [21]:
df.groupby("Departamento")["Salário"].min()

Departamento
RH        4000
TI        5000
Vendas    3000
Name: Salário, dtype: int64

In [22]:
df.groupby("Departamento")["Salário"].count()

Departamento
RH        2
TI        2
Vendas    2
Name: Salário, dtype: int64

In [24]:
df.groupby("Departamento")["Salário"].count()

Departamento
RH        2
TI        2
Vendas    2
Name: Salário, dtype: int64

In [27]:
df.groupby("Departamento")["Salário"].nunique()

Departamento
RH        2
TI        1
Vendas    2
Name: Salário, dtype: int64

In [39]:
df.groupby("Estado")["Salário"].sum()

Estado
Belo Horizonte     4200
Rio de Janeiro     9500
São Paulo         13000
Name: Salário, dtype: int64

In [36]:
df.groupby("Departamento").agg({"Salário": ["mean", "median", "min", "max", "count", "nunique"]})

             Salário
                mean  median   min   max count nunique
Departamento
RH            4100.0  4100.0  4000  4200     2       2
TI            6000.0  6000.0  6000  6000     2       1
Vendas        3250.0  3250.0  3000  3500     2       2

In [37]:
df.groupby("Departamento").agg({"Nome": ["count"], "Salário": ["max"]})

              Nome Salário
             count     max
Departamento
RH               2    4200
TI               2    6000
Vendas           2    3500