In [1]:
import numpy as np
import pandas as pd

In [2]:
usuarios = {
    "ID_usuario": [1, 2, 3],
    "Nome": ["Maria", "Bruno", "Joao"],
    "Cidade": ["São Paulo", "Rio", "Belo Horizonte"]
}

compras = {
    "ID_usuario": [1, 2, 1, 1, 3, 3, 2, 3],
    "Produto": ["Notebook", "Camera", "Camiseta", "Camiseta", "Caneca", "Caneca", "Calça", "Calça"],
    "Valor": [2000, 1000, 70, 60, 50, 50, 120, 100]
}

usuarios_novos = {
    "ID_usuario": [4, 5],
    "Nome": ["Pedro", "Marcos"]
}

In [3]:
usuarios_df = pd.DataFrame(usuarios)
compras_df = pd.DataFrame(compras)
usuarios_novos_df = pd.DataFrame(usuarios_novos)

In [4]:
usuarios_df

   ID_usuario   Nome          Cidade
0           1  Maria       São Paulo
1           2  Bruno             Rio
2           3   Joao  Belo Horizonte

In [5]:
compras_df

   ID_usuario   Produto  Valor
0           1  Notebook   2000
1           2    Camera   1000
2           1  Camiseta     70
3           1  Camiseta     60
4           3    Caneca     50
5           3    Caneca     50
6           2     Calça    120
7           3     Calça    100

In [6]:
usuarios_novos_df

   ID_usuario    Nome
0           4   Pedro
1           5  Marcos

In [7]:
pd.concat([usuarios_df, usuarios_novos_df])

   ID_usuario    Nome          Cidade
0           1   Maria       São Paulo
1           2   Bruno             Rio
2           3    Joao  Belo Horizonte
0           4   Pedro             NaN
1           5  Marcos             NaN

In [8]:
usuarios_geral = pd.concat([usuarios_df, usuarios_novos_df])

In [9]:
usuarios_geral

   ID_usuario    Nome          Cidade
0           1   Maria       São Paulo
1           2   Bruno             Rio
2           3    Joao  Belo Horizonte
0           4   Pedro             NaN
1           5  Marcos             NaN

In [14]:
usuarios_geral.fillna({"Cidade": "Cidade Desconhecida"}, inplace=True)

In [15]:
usuarios_geral

   ID_usuario    Nome               Cidade
0           1   Maria            São Paulo
1           2   Bruno                  Rio
2           3    Joao       Belo Horizonte
0           4   Pedro  Cidade Desconhecida
1           5  Marcos  Cidade Desconhecida

In [16]:
compras_df

   ID_usuario   Produto  Valor
0           1  Notebook   2000
1           2    Camera   1000
2           1  Camiseta     70
3           1  Camiseta     60
4           3    Caneca     50
5           3    Caneca     50
6           2     Calça    120
7           3     Calça    100

In [24]:
# Left => manter valores do df da esquerda e associar aos valores da direita
# Right => manter valores do df da direita e associar aos valores da esquerda
# Inner => apenas o que tem em comum

compras_df.merge(usuarios_geral, how="left", on="ID_usuario")

   ID_usuario   Produto  Valor   Nome          Cidade
0           1  Notebook   2000  Maria       São Paulo
1           2    Camera   1000  Bruno             Rio
2           1  Camiseta     70  Maria       São Paulo
3           1  Camiseta     60  Maria       São Paulo
4           3    Caneca     50   Joao  Belo Horizonte
5           3    Caneca     50   Joao  Belo Horizonte
6           2     Calça    120  Bruno             Rio
7           3     Calça    100   Joao  Belo Horizonte

In [28]:
compras_df.merge(usuarios_geral, how="right", on="ID_usuario")

   ID_usuario   Produto   Valor    Nome               Cidade
0           1  Notebook  2000.0   Maria            São Paulo
1           1  Camiseta    70.0   Maria            São Paulo
2           1  Camiseta    60.0   Maria            São Paulo
3           2    Camera  1000.0   Bruno                  Rio
4           2     Calça   120.0   Bruno                  Rio
5           3    Caneca    50.0    Joao       Belo Horizonte
6           3    Caneca    50.0    Joao       Belo Horizonte
7           3     Calça   100.0    Joao       Belo Horizonte
8           4       NaN     NaN   Pedro  Cidade Desconhecida
9           5       NaN     NaN  Marcos  Cidade Desconhecida

In [25]:
compras_df.merge(usuarios_geral, how="inner", on="ID_usuario")

   ID_usuario   Produto  Valor   Nome          Cidade
0           1  Notebook   2000  Maria       São Paulo
1           2    Camera   1000  Bruno             Rio
2           1  Camiseta     70  Maria       São Paulo
3           1  Camiseta     60  Maria       São Paulo
4           3    Caneca     50   Joao  Belo Horizonte
5           3    Caneca     50   Joao  Belo Horizonte
6           2     Calça    120  Bruno             Rio
7           3     Calça    100   Joao  Belo Horizonte